jobs:
 # - name: sample_runShCI
  #  type: runSh
  #  steps:
  #    - IN: sample_prodcipipelines_runCI
       # showBuildStatus: true
  #    - TASK:
    #    - script: ls
  
  - name: oldtritonint-runsh
    type: runSh
    steps:
      - IN: sample_prodCiPipelinesRepo
       # showBuildStatus: true
      - IN: ship_oldtripubint
      - TASK:
        - script: echo $SHIPOLDTRIPUBINT_INTEGRATION_NAME
        - script: echo $SHIP_OLDTRIPUBINT_INTEGRATION_USERNAME
        - script: echo $SHIP_OLDTRIPUBINT_INTEGRATION_VALIDITYPERIOD
        - script: echo $SHIP_OLDTRIPUBINT_INTEGRATION_CERTIFICATES
        - script: echo $SHIP_OLDTRIPUBINT_INTEGRATION_PRIVATEKEY
      #- OUT: test_out_img
 
  - name: newtritonint-runsh
    type: runSh
    allowPublicAccess: false
    steps:      
      - IN: sample_prodCiPipelinesRepo
       # showBuildStatus: true
      - IN: ship_newtripubint
      - TASK:
        - script: echo $SHIPNEWTRIPUBINT_INTEGRATION_NAME
        - script: echo $SHIP_NEWTRIPUBINT_INTEGRATION_USERNAME
        - script: echo $SHIP_NEWTRIPUBINT_INTEGRATION_VALIDITYPERIOD
        - script: echo $SHIP_NEWTRIPUBINT_INTEGRATION_CERTIFICATES
        - script: echo $SHIP_NEWTRIPUBINT_INTEGRATION_PRIVATEKEY
  
  - name: oldtritonclu-runsh
    type: runSh
    steps:
      - IN: oldtriton_cluster
      - TASK:
        - script: echo $OLDTRITON_CLUSTER_INTEGRATION_NAME
        - script: echo $OLDTRITON_CLUSTER_INTEGRATION_USERNAME
        - script: echo $OLDTRITON_CLUSTER_INTEGRATION_VALIDITYPERIOD
        - script: echo $OLDTRITON_CLUSTER_INTEGRATION_CERTIFICATES
        - script: echo $OLDTRITON_CLUSTER_INTEGRATION_PRIVATEKEY

  - name: newtritonclu-runsh
    type: runSh
    allowPublicAccess: false
    steps:      
      - IN: newtriton_cluster
      - TASK:
        - script: echo $NEWTRITON_CLUSTER_INTEGRATION_NAME
        - script: echo $NEWTRITON_CLUSTER_INTEGRATION_USERNAME
        - script: echo $NEWTRITON_CLUSTER_INTEGRATION_VALIDITYPERIOD
        - script: echo $NEWTRITON_CLUSTER_INTEGRATION_CERTIFICATES
        - script: echo $NEWTRITON_CLUSTER_INTEGRATION_PRIVATEKEY
        
  - name: manifest_dep
    type: manifest
    steps:
      - IN: deploy_img       
  
  - name: manifest_dep2
    type: manifest
    steps:
      - IN: deploy_img2
      
  - name: deploy-newtritonupgradetoplevel
    type: deploy
    method: upgrade
    workflow: serial
    steps:      
      - IN: manifest_dep
      #- IN: manifest_dep2
      - IN: newtriton_cluster
      - IN: tripub_dopts
      - TASK: managed  
    flags: new-triton
  
  - name: deploy-newtritonupgradebottom
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: newtriton_cluster
      - IN: tripub_dopts
      - TASK: managed 
        deployMethod: upgrade
    flags: new-triton
    
  - name: deploy-newtritondefault
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: newtriton_cluster
      - IN: tripub_dopts
      - TASK: managed  
    flags: new-triton
  
  - name: deploy-oldtritonupgradetoplevel
    type: deploy
    method: upgrade
    workflow: serial
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: oldtriton_cluster
      - IN: tripub_dopts
      - TASK: managed  
    flags: old-triton
  
  - name: deploy-oldtritonupgradebottom
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: oldtriton_cluster
      - IN: tripub_dopts
      - TASK: managed 
        deployMethod: upgrade
    flags: old-triton
    
  - name: deploy-oldtritondefault
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: oldtriton_cluster
      - IN: tripub_dopts
      - TASK: managed  
    flags: old-triton
  
  - name: deploy-oldtritonbluegreen
    type: deploy
    workflow: parallel
    steps:      
      - IN: manifest_dep
      - IN: manifest_dep2
      - IN: oldtriton_cluster
      - IN: tripub_dopts
      - TASK: managed  
    flags: old-triton
  
  - name: deploy-oldtritonreplace
    type: deploy
    method: replace
    workflow: parallel
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: oldtriton_cluster
      - IN: tripub_dopts
      - TASK: managed  
    flags: old-triton
    
  - name: deploy-newtritonbluegreen
    type: deploy
    #workflow: parallel
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: newtriton_cluster
      - IN: tripub_dopts
      - TASK: managed 
        deployMethod: blueGreen
    flags: new-triton
  
  - name: deploy-newtritonreplace
    type: deploy
    #method: replace
    #workflow: parallel
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: newtriton_cluster
      - IN: tripub_dopts
      - TASK: managed 
        deployMethod: replace
    flags: new-triton
    