jobs:
 # - name: sample_runShCI
  #  type: runSh
  #  steps:
  #    - IN: sample_prodcipipelines_runCI
       # showBuildStatus: true
  #    - TASK:
    #    - script: ls
  
  - name: oldddcint-runsh
    type: runSh
    steps:
      - IN: sample_prodCiPipelinesRepo
       # showBuildStatus: true
      - IN: ship_oldkubeint
      - TASK:
        - script: echo SHIP_OLDKUBEINT_INTEGRATION_NAME=$SHIP_OLDKUBEINT_INTEGRATION_NAME
        - script: echo SHIP_OLDKUBEINT_INTEGRATION_CLUSTERACCESSTYPE=$SHIP_OLDKUBEINT_INTEGRATION_CLUSTERACCESSTYPE
        - script: echo SHIP_OLDKUBEINT_INTEGRATION_MASTERKUBECONFIGCONTENT=$SHIP_OLDKUBEINT_INTEGRATION_MASTERKUBECONFIGCONTENT
        - script: echo SHIP_OLDKUBEINT_INTEGRATION_BASTIONKUBECONFIGCONTENT=$SHIP_OLDKUBEINT_INTEGRATION_BASTIONKUBECONFIGCONTENT
        - script: echo SHIP_OLDKUBEINT_INTEGRATION_BASTIONHOSTIP=$SHIP_OLDKUBEINT_INTEGRATION_BASTIONHOSTIP
        - script: echo SHIP_OLDKUBEINT_INTEGRATION_BASTIONPRIVATEKEY=$SHIP_OLDKUBEINT_INTEGRATION_BASTIONPRIVATEKEY
        - script: echo SHIP_OLDKUBEINT_INTEGRATION_BASTIONPUBLICKEY=$SHIP_OLDKUBEINT_INTEGRATION_BASTIONPUBLICKEY
      #- OUT: test_out_img
 
  - name: newddcint-runsh
    type: runSh
    allowPublicAccess: false
    steps:      
      - IN: sample_prodCiPipelinesRepo
       # showBuildStatus: true
      - IN: ship_newkubeint
      - TASK:
        - script: echo SHIP_NEWKUBEINT_INTEGRATION_NAME=$SHIP_NEWKUBEINT_INTEGRATION_NAME
        - script: echo SHIP_NEWKUBEINT_INTEGRATION_CLUSTERACCESSTYPE=$SHIP_NEWKUBEINT_INTEGRATION_CLUSTERACCESSTYPE
        - script: echo SHIP_NEWKUBEINT_INTEGRATION_MASTERKUBECONFIGCONTENT=$SHIP_NEWKUBEINT_INTEGRATION_MASTERKUBECONFIGCONTENT
        - script: echo SHIP_NEWKUBEINT_INTEGRATION_BASTIONKUBECONFIGCONTENT=$SHIP_NEWKUBEINT_INTEGRATION_BASTIONKUBECONFIGCONTENT
        - script: echo SHIP_NEWKUBEINT_INTEGRATION_BASTIONHOSTIP=$SHIP_NEWKUBEINT_INTEGRATION_BASTIONHOSTIP
        - script: echo SHIP_NEWKUBEINT_INTEGRATION_BASTIONPRIVATEKEY=$SHIP_NEWKUBEINT_INTEGRATION_BASTIONPRIVATEKEY
        - script: echo SHIP_NEWKUBEINT_INTEGRATION_BASTIONPUBLICKEY=$SHIP_NEWKUBEINT_INTEGRATION_BASTIONPUBLICKEY
  
  - name: oldddcclu-runsh
    type: runSh
    steps:
      - IN: oldkube_cluster
      - TASK:
        - script: echo OLDKUBE_CLUSTER_INTEGRATION_NAME=$OLDKUBE_CLUSTER_INTEGRATION_NAME
        - script: echo OLDKUBE_CLUSTER_INTEGRATION_CLUSTERACCESSTYPE=$OLDKUBE_CLUSTER_INTEGRATION_CLUSTERACCESSTYPE
        - script: echo OLDKUBE_CLUSTER_INTEGRATION_MASTERKUBECONFIGCONTENT=$OLDKUBE_CLUSTER_INTEGRATION_MASTERKUBECONFIGCONTENT
        - script: echo OLDKUBE_CLUSTER_INTEGRATION_BASTIONKUBECONFIGCONTENT=$OLDKUBE_CLUSTER_INTEGRATION_BASTIONKUBECONFIGCONTENT
        - script: echo OLDKUBE_CLUSTER_INTEGRATION_BASTIONHOSTIP=$OLDKUBE_CLUSTER_INTEGRATION_BASTIONHOSTIP
        - script: echo OLDKUBE_CLUSTER_INTEGRATION_BASTIONPRIVATEKEY=$OLDKUBE_CLUSTER_INTEGRATION_BASTIONPRIVATEKEY
        - script: echo OLDKUBE_CLUSTER_INTEGRATION_BASTIONPUBLICKEY=$OLDKUBE_CLUSTER_INTEGRATION_BASTIONPUBLICKEY
      #- OUT: test_out_img
 
  - name: newddcclu-runsh
    type: runSh
    allowPublicAccess: false
    steps:      
      - IN: newkube_cluster
      - TASK:
        - script: echo NEWKUBE_CLUSTER_INTEGRATION_NAME=$NEWKUBE_CLUSTER_INTEGRATION_NAME
        - script: echo NEWKUBE_CLUSTER_INTEGRATION_CLUSTERACCESSTYPE=$NEWKUBE_CLUSTER_INTEGRATION_CLUSTERACCESSTYPE
        - script: echo NEWKUBE_CLUSTER_INTEGRATION_MASTERKUBECONFIGCONTENT=$NEWKUBE_CLUSTER_INTEGRATION_MASTERKUBECONFIGCONTENT
        - script: echo NEWKUBE_CLUSTER_INTEGRATION_BASTIONKUBECONFIGCONTENT=$NEWKUBE_CLUSTER_INTEGRATION_BASTIONKUBECONFIGCONTENT
        - script: echo NEWKUBE_CLUSTER_INTEGRATION_BASTIONHOSTIP=$NEWKUBE_CLUSTER_INTEGRATION_BASTIONHOSTIP
        - script: echo NEWKUBE_CLUSTER_INTEGRATION_BASTIONPRIVATEKEY=$NEWKUBE_CLUSTER_INTEGRATION_BASTIONPRIVATEKEY
        - script: echo NEWKUBE_CLUSTER_INTEGRATION_BASTIONPUBLICKEY=$NEWKUBE_CLUSTER_INTEGRATION_BASTIONPUBLICKEY
        
  - name: manifest_dep
    type: manifest
    steps:
      - IN: deploy_img       
  
  - name: manifest_dep2
    type: manifest
    steps:
      - IN: deploy_img2
      
  - name: deploy-newkubeupgradetoplevel
    type: deploy
    method: upgrade
    workflow: serial
    steps:      
      - IN: manifest_dep
      #- IN: manifest_dep2
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: new-kube
  
  - name: deploy-newkubeupgradebottom
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed 
        deployMethod: upgrade
    flags: new-kube
    
  - name: deploy-newkubedefault
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: new-kube
  
  - name: deploy-oldkubeupgradetoplevel
    type: deploy
    method: upgrade
    workflow: serial
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: old-kube
  
  - name: deploy-oldkubeupgradebottom
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed 
        deployMethod: upgrade
    flags: old-kube
    
  - name: deploy-oldkubedefault
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: old-kube
    
  - name: deploy-oldkubebluegreen
    type: deploy
    workflow: parallel
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: old-kube
  
  - name: deploy-oldkubereplace
    type: deploy
    method: replace
    workflow: parallel
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: old-kube
    
  - name: deploy-newkubebluegreen
    type: deploy
    #workflow: parallel
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed 
        deployMethod: blueGreen
    flags: new-kube
  
  - name: deploy-newkubereplace
    type: deploy
    #method: replace
    #workflow: parallel
    steps:      
      - IN: manifest_dep
      #- IN: manifest_dep2
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed 
        deployMethod: replace
    flags: new-kube
    