jobs:
 # - name: sample_runShCI
  #  type: runSh
  #  steps:
  #    - IN: sample_prodcipipelines_runCI
       # showBuildStatus: true
  #    - TASK:
    #    - script: ls
  
  - name: oldddcint-runsh
    type: runSh
    steps:
      - IN: sample_prodCiPipelinesRepo
       # showBuildStatus: true
      - IN: ship_oldkubeint
      - TASK:
        - script: echo $SHIP_OLDKUBEINT_INTEGRATION_USERNAME
        - script: echo $SHIP_OLDKUBEINT_INTEGRATION_PASSWORD
        - script: echo $SHIP_OLDKUBEINT_INTEGRATION_URL
      #- OUT: test_out_img
 
  - name: newddcint-runsh
    type: runSh
    allowPublicAccess: false
    steps:      
      - IN: sample_prodCiPipelinesRepo
       # showBuildStatus: true
      - IN: ship_newkubeint
      - TASK:
        - script: echo $SHIP_NEWKUBEINT_INTEGRATION_USERNAME
        - script: echo $SHIP_NEWKUBEINT_INTEGRATION_PASSWORD
        - script: echo $SHIP_NEWKUBEINT_INTEGRATION_URL
  
  - name: oldddcclu-runsh
    type: runSh
    steps:
      - IN: oldkube_cluster
      - TASK:
        - script: echo $OLDKUBE_CLUSTER_INTEGRATION_USERNAME
        - script: echo $OLDKUBE_CLUSTER_INTEGRATION_PASSWORD
        - script: echo $OLDKUBE_CLUSTER_INTEGRATION_URL
      #- OUT: test_out_img
 
  - name: newddcclu-runsh
    type: runSh
    allowPublicAccess: false
    steps:      
      - IN: newkube_cluster
      - TASK:
        - script: echo $NEWKUBE_CLUSTER_INTEGRATION_USERNAME
        - script: echo $NEWKUBE_CLUSTER_INTEGRATION_PASSWORD
        - script: echo $NEWKUBEC_CLUSTER_INTEGRATION_URL
        
  - name: manifest_dep
    type: manifest
    steps:
      - IN: deploy_img       
  
  - name: manifest_dep2
    type: manifest
    steps:
      - IN: deploy_img2
      
  - name: deploy-newkubeupgradetoplevel
    type: deploy
    method: upgrade
    workflow: serial
    steps:      
      - IN: manifest_dep
      #- IN: manifest_dep2
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: new-kube
  
  - name: deploy-newkubeupgradebottom
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed 
        deployMethod: upgrade
    flags: new-kube
    
  - name: deploy-newkubedefault
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: new-kube
  
  - name: deploy-oldkubeupgradetoplevel
    type: deploy
    method: upgrade
    workflow: serial
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: old-kube
  
  - name: deploy-oldkubeupgradebottom
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed 
        deployMethod: upgrade
    flags: old-kube
    
  - name: deploy-oldkubedefault
    type: deploy
    steps:      
      - IN: manifest_dep
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: old-kube
    
  - name: deploy-oldkubebluegreen
    type: deploy
    workflow: parallel
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: old-kube
  
  - name: deploy-oldkubereplace
    type: deploy
    method: replace
    workflow: parallel
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: oldkube_cluster
      - IN: kube_dopts
      - TASK: managed  
    flags: old-kube
    
  - name: deploy-newkubebluegreen
    type: deploy
    #workflow: parallel
    steps:      
      - IN: manifest_dep
     # - IN: manifest_dep2
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed 
        deployMethod: blueGreen
    flags: new-kube
  
  - name: deploy-newkubereplace
    type: deploy
    #method: replace
    #workflow: parallel
    steps:      
      - IN: manifest_dep
      #- IN: manifest_dep2
      - IN: newkube_cluster
      - IN: kube_dopts
      - TASK: managed 
        deployMethod: replace
    flags: new-kube
    